#!/bin/sh

BASEDIR=`dirname $0`

pushd $BASEDIR > /dev/null

/opt/helixutils/create-git-changelog --package=helixcore --dir=$BASEDIR
dpkg-buildpackage -uc -us -b -rfakeroot
mkdir -p dist
mv ../helixcore*.deb dist
rm -f  ../helixcore*.changes

popd > /dev/null

