_ = lambda x: x

HELIX_ERROR = _('HELIX_ERROR')
HELIX_SERVICE_UNAVAILABLE = _('HELIX_SERVICE_UNAVAILABLE')
HELIX_REQUEST_PROCESSING_ERROR = _('HELIX_REQUEST_PROCESSING_ERROR')
HELIX_UNKNOWN_ACTION_ERROR = _('HELIX_UNKNOWN_ACTION_ERROR')
HELIX_DATA_INTEGRITY_ERROR = _('HELIX_DATA_INTEGRITY_ERROR')
HELIX_ACTION_NOT_ALLOWED_ERROR = _('HELIX_ACTION_NOT_ALLOWED_ERROR')
HELIX_APPLICATION_ERROR = _('HELIX_APPLICATION_ERROR')
HELIX_VALIDATION_ERROR = _('HELIX_VALIDATION_ERROR')
HELIX_FORMAT_ERROR = _('HELIX_FORMAT_ERROR')
HELIX_AUTH_ERROR = _('HELIX_AUTH_ERROR')